"""
A generic setup.py file generated by django duke client 0.0.1
"""

from setuptools import setup, find_packages

setup(
    name = "django-company",
    version = "0.0.1",
    url = "https://github.com/h3/django-company",
    license = "",
    description = "",
    author = 'Maxime Haineault',
    packages = find_packages(),
    package_dir = {'': '.'},
    install_requires = [],
)
